spring:
  application:
    name: "task"
  profiles:
    active: "dev"

#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#  logging:
#    level:
#      org:
#        hibernate:
#          type: trace